services:
  mongodb:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  init-auth:
    build: .
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/admin
    command: python scripts/init_auth.py
    volumes:
      - ./data:/app/data

  test:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - init-auth
    environment:
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/admin
    command: poetry run pytest tests/ -v
    volumes:
      - ./tests:/app/tests

  migration:
    build: .
    depends_on:
      - test
    environment:
      MONGODB_URI: mongodb://${MONGO_ADMIN_USER}:${MONGO_ADMIN_PASSWORD}@mongodb:27017/${MONGO_DATABASE}
    volumes:
      - ./data:/app/data

volumes:
  mongodb_data: