version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  init-auth:
    build: .
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://root:example@mongodb:27017/admin
    command: python scripts/init_auth.py
    volumes:
      - ./data:/app/data

  test:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - init-auth
    environment:
      MONGODB_URI: mongodb://admin_user:admin_password_2025@mongodb:27017/healthcare
    command: poetry run pytest tests/ -v
    volumes:
      - ./tests:/app/tests

  migration:
    build: .
    depends_on:
      - test
    environment:
      MONGODB_URI: mongodb://admin_user:admin_password_2025@mongodb:27017/healthcare
    volumes:
      - ./data:/app/data

volumes:
  mongodb_data: